### ISSUE TITLE
with SNT

### ISSUE THREAD

**Issue by anna06test** [Anna06TestORG/ORG1#11]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x95f27acdaf1a6d730f8e2c4f6b8c284f0afc8d3e](https://ropsten.etherscan.io/address/0x95f27acdaf1a6d730f8e2c4f6b8c284f0afc8d3e)
![QR Code](https://test-openbounty.status.im/qr/Anna06TestORG/ORG1/bounty/11/72da5509b40d9ac1c1fb4ed23b65f63e8209314f7b7b99620253a2ea64ca8180/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://test-openbounty.status.im](https://test-openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
