### ISSUE TITLE
Close me

### ISSUE THREAD

**Issue by anna06test** [Anna06TestORG/ORG1#3]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x77bf593b423451dc7604520fef0dbcb1961afa72](https://ropsten.etherscan.io/address/0x77bf593b423451dc7604520fef0dbcb1961afa72)
![QR Code](https://openbounty.status.im:444/qr/Anna06TestORG/ORG1/bounty/3/1cf9627e6044c2a45b88690313e925e8812824032a3d85006464614f0ef699f2/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
